application: wifi2use
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/.*
  script: service.application
- url: /*
  script: wifi2use.application

libraries:
- name: webapp2
  version: latest
